version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: